### ISSUE TITLE
Change subject of newsletter doesnt save the first time

### ISSUE THREAD

**Issue by RichardMailcamp** [EDMdesigner/editor-issues#44] opened 2016-06-24 07:39 UTC
Hi,

Somehow when changing the subject of the NL before sending, it doesn't save the changes that are made, but when trying a second time, it does.

Any thoughts? 

Rich

**Comment by gyulanemeth** [comment] 2016-06-24 08:49
Hello, can you please attach some screenshots to help us understand what the issue is?

**Comment by RichardMailcamp** [comment] 2016-06-24 09:05
Well, there isn’t much to attach. When you’re in the send newsletter screen within Mailcamp, the change subject of newsletter doesn’t save. On the other hand, after thinking about it again (I sent this mail by request of one f my colleagues) I’m wondering if this is something that is going wrong with the communication with EDM designer or if this is a bug in our software….Hmmm

So, is the saving of the subject of the NL something that is communicated with you before sending? If not, sorry to have wasted your time :S

Met vriendelijke groet,
Richard Crombie

[mc_mail_logo]
Bezoekadres
Nieuwe Hemweg 2
1013 BG Amsterdam

Tel.: +31 (0) 20 705 85 00
Support: support@mailcamp.nlmailto:support@mailcamp.nl
E-mail: richard@mailcamp.nlmailto:richard@mailcamp.nl
Web: www.mailcamp.nlhttp://www.mailcamp.nl/

Van: Gyula Németh [mailto:notifications@github.com]
Verzonden: Friday, June 24, 2016 10:50
Aan: EDMdesigner/editor-issues editor-issues@noreply.github.com
CC: Richard Crombie richard@mailcamp.nl; Author author@noreply.github.com
Onderwerp: Re: [EDMdesigner/editor-issues] Change subject of newsletter doesnt save the first time (#44)

Hello, can you please attach some screenshots to help us understand what the issue is?

**Comment by iamgaborgithub** [comment] 2020-05-27 14:28
Dear Richard,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com

**Closed as completed by iamgaborgithub** 2020-05-27 14:28 UTC
