### ISSUE TITLE
Problem in changing font color in text block

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/editor-issues#38] opened 2016-05-23 08:37 UTC
Dear Support,

One of our client encountered below problem when changing font color in text block, and the font family and font size suddenly changed.

Tested browser: Chrome in Max OS X (sometime this also happens in Windows Chrome)
[2016-05-23_10-51-29.zip](https://github.com/EDMdesigner/editor-issues/files/277092/2016-05-23_10-51-29.zip)

Please help investigate, thanks.

**Comment by gyulanemeth** [comment] 2016-06-08 14:58
Thank you for the attached video, we will try to reproduce this issue.

**Comment by iamgaborgithub** [comment] 2020-05-27 14:27
Dear confettidc,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com

**Closed as completed by iamgaborgithub** 2020-05-27 14:27 UTC
