### ISSUE TITLE
Images resizes on multi upload

### ISSUE THREAD

**Issue by Mailcamp** [EDMdesigner/editor-issues#19] opened 2016-03-04 12:42 UTC
When we upload multiple images in de editor, the original sizes changes, this does not happend when we only upload one image at the time.

See screenhot for example:
[Screenshot](https://p4.zdusercontent.com/attachment/239229/LyKkC8fPQg1feelbon0zeymXw?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..f6k7tzC1DtUstvX8Ii0P4g.XsGcO7wb5l7ziMwp-o_XY8-h1J81f5Vu6ddp6awlvyGu7lekLZTCClqqlfHB0hOMC6mYdjYNZ2arC_HIiKv4SzERGBG6lz5azLGeQdadMcTwWuEGsCmn1hAitnJO0pAV5WvpTraAF8KZ77k9hAY1kn9M7I7E7E3mPDaVJfra1zs2g9F51Qqif2DNfjS_YdBR2dwolMO0sOlfCWggbpqfYFqDmjEIdwz-kbcY3gMJhiXiotsHri0zpqCW5xjFBwj0Pgn43Y4kQTbllKuQcDuc0yW8als5nnWl-18JdaT6aTY.QtxwJ2s6OYkaAX54x9Yb0w)

**Comment by gyulanemeth** [comment] 2016-03-09 13:28
Thank you for reporting this, we opened a ticket and will fix it soon.

**Comment by gyulanemeth** [comment] 2016-03-29 12:14
Hello, we simply could not reproduce this issue. Can you make a video about this issue please?

**Comment by iamgaborgithub** [comment] 2020-05-27 13:58
Dear Mailcamp,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com

**Closed as completed by iamgaborgithub** 2020-05-27 13:58 UTC
