### ISSUE TITLE
Image group with custom gallery - cannot change the image

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#16] opened 2016-03-01 07:58 UTC
Image group with custom gallery – after changing layout you cannot change the image. Please see link: https://agnieszka.tinytake.com/sf/NDY5NzI4XzI1MTk1Mjk

**Comment by ghost** [comment] 2016-03-10 14:49
We opened a ticket and will fix it soon. 
Thank you for reporting this!

**Comment by balintsoos** [comment] 2016-03-18 14:16
Can you tell us which editor version you are using? I can't reproduce this bug in the latest version. Thank you in advance!

**Comment by agnieszkakowalska** [comment] 2016-03-18 14:44
It's the latest version, I've double checked right now. Also please be aware that this is a custom image gallery.

**Comment by balintsoos** [comment] 2016-03-18 15:15
Thanks for your reply, I continue the investigation.

**Comment by balintsoos** [comment] 2016-03-30 08:08
This issue has been resolved. We will release next version of the editor in the upcoming days.

**Comment by iamgaborgithub** [comment] 2020-05-27 13:58
Dear agnieszkakowalska,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com

**Closed as completed by iamgaborgithub** 2020-05-27 13:58 UTC
Labels: ready
